{% set version = "52" %}

package:
  name: cromwell
  version: {{ version }}

source:
  - url: https://github.com/broadinstitute/cromwell/releases/download/{{ version }}/cromwell-{{ version }}.jar
    sha256: 4b3195420d59d7ea129c3d690c9a1cc323403d9c85965ed7c2a37144af13ffa1
    folder: cromwell
  - url: https://github.com/broadinstitute/cromwell/releases/download/{{ version }}/womtool-{{ version }}.jar
    sha256: 67331af5a4850c5c04e521682c6618c93c475c041f254121849ddb4cffde5c16
    folder: womtool

build:
  # Cannot build on Windows because findutils is not available
  skip: true  # [win]
  number: 0

requirements:
  run:
    - openjdk >=8,<9
    - python
    - findutils

test:
  commands:
    - cromwell --version 2>&1 | grep "cromwell"
    - womtool --help 2>&1 | grep "Usage"

about:
  home: https://github.com/broadinstitute/cromwell
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Workflow Management System geared towards scientific workflows described in WDL
  doc_url: https://cromwell.readthedocs.io/en/stable/
  dev_url: https://github.com/broadinstitute/cromwell

extra:
  recipe-maintainers:
    - notestaff
    - chapmanb
    - micknudsen
    - rhpvorderman
