travis:
  secure:
    BINSTAR_TOKEN: SG688vzfUFUAZu9c3v8ayOBU11cGPOXkp+O6i2ReiA7s2Ga/krNMRY8km4g7NjYlijfDhWIv+e9vVRZHtvd9K5Ytu65UWO+ndNIk3SF4uMMoMS04+EGZ3wlQJxV+ekdhKnANe/ZKeLpiC6atm21pXHGHfxrflaMCHTsd8ov7pJAgWYyzneldxfxh8TZADjKW0YhzWBmK/8d5pxtgKyoDVIJkTWfZylwobLIka5cDyMEXWY5Pl7HPgjK4nA/WT9mnsapo2R3mut8d+80VkM7h7hTOGI9dLVUK/M2+OVWb3hF9tGqn/vECwdh5YyNa6miXpWha5IgYIs8bvpTbf6YAWMxIJQKMwZKx4c06xsDX2Udb+V9kUX8aBkxevRajg2XrNddFM/PTFYlD/gCpaJcfWGuPGVMAY4kkIFE18HftviVxQJbnf3CjvK0kA33DGmd1MJxx0yYA8x6KRZDgj3ZtAmfxVm5mOt6evPiM4yuWTta1FgfQN9rPHnevtO+h3nKRkahsoG+V54oNQqPoCdJUyp2c4h3STJcIBnr6MAPD2O3j/QJDzIsopbmZDwlnjDofEDqhDllN/W7xO1Xhxxwf7vIG0jSugMti854otBQMilz4JqxKsfULTUwrnMA+akXQUszGlApuCu4O9PTBTj5Gf4dWjhtBUU1ijb70JPtMZNI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
